CREATE TYPE "sex_enum" AS ENUM (
  'male',
  'female'
);

CREATE TYPE "age_group_enum" AS ENUM (
  'open',
  '50+',
  '60+',
  '70+',
  'under 21',
  'under 18',
  'under 16',
  'under 14'
);

CREATE TYPE "type_participant_score_enum" AS ENUM (
  'competition',
  'practice'
);

CREATE TYPE "status_enum" AS ENUM (
  'eligible',
  'ineligible',
  'in progress',
  'pending'
);

CREATE TYPE "type_request_form_enum" AS ENUM (
  'participating',
  'recording'
);

CREATE TYPE "action_request_form_enum" AS ENUM (
  'enrol',
  'withdraw'
);

CREATE TYPE "unit_of_length_enum" AS ENUM (
  'mm',
  'cm',
  'dm',
  'm',
  'dam',
  'hm',
  'km',
  'in',
  'ft',
  'yd',
  'mi',
  'nmi',
  'µm',
  'nm',
  'pm',
  'fm',
  'ly',
  'au',
  'pc'
);

CREATE TABLE "account" (
  "account_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email_address" varchar(255) NOT NULL,
  "hash_password" varchar(255) NOT NULL,
  "fullname" varchar(2253) NOT NULL,
  "country" varchar(255) NOT NULL,
  "date_of_birth" date NOT NULL,
  "sex" sex_enum NOT NULL,
  "avatar_url" text DEFAULT 'https://ghcpcyvethwdzzgyymfp.supabase.co/storage/v1/object/public/User%20Avatar/Account_Avatar/Default_Avatar.jpg',
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "admin" (
  "admin_id" int PRIMARY KEY
);

CREATE TABLE "recorder" (
  "recorder_id" int PRIMARY KEY,
  "year_of_experience" int NOT NULL,
  "background" text
);

CREATE TABLE "recording" (
  "recorder_id" int,
  "competition_id" int,
  "round_id" int,
  PRIMARY KEY ("recorder_id", "competition_id", "round_id")
);

CREATE TABLE "archer" (
  "archer_id" int PRIMARY KEY,
  "default_equipment_id" int NOT NULL,
  "club_id" int,
  "year_of_experience" int NOT NULL,
  "background" text
);

CREATE TABLE "club" (
  "club_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "creator_id" int NOT NULL,
  "age_group" age_group_enum NOT NULL,
  "open_to_join" bool NOT NULL DEFAULT true,
  "formation_date" date NOT NULL,
  "club_logo_url" text NOT NULL DEFAULT 0
);

CREATE TABLE "australia_archery_federation" (
  "member_id" int PRIMARY KEY,
  "date_joined" int
);

CREATE TABLE "participating" (
  "participant_id" int,
  "event_context_id" text NOT NULL,
  "score_1st_arrow" smallint NOT NULL DEFAULT 0,
  "score_2nd_arrow" smallint NOT NULL DEFAULT 0,
  "score_3rd_arrow" smallint NOT NULL DEFAULT 0,
  "score_4th_arrow" smallint NOT NULL DEFAULT 0,
  "score_5st_arrow" smallint NOT NULL DEFAULT 0,
  "score_6st_arrow" smallint NOT NULL DEFAULT 0,
  "sum_score" smallint NOT NULL DEFAULT 0,
  "datetime" timestamptz NOT NULL,
  "type" type_participant_score_enum NOT NULL DEFAULT 'competition',
  "status" status_enum NOT NULL DEFAULT 'pending',
  PRIMARY KEY ("participant_id", "event_context_id", "type")
);

CREATE TABLE "event_context" (
  "event_context_id" text PRIMARY KEY,
  "yearly_club_championship_id" int,
  "competition_id" int NOT NULL,
  "round_id" int NOT NULL,
  "range_id" int NOT NULL,
  "end_order" int NOT NULL
);

CREATE TABLE "yearly_club_championship" (
  "yearly_club_championship_id" int PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "year" int NOT NULL,
  "creator_id" int NOT NULL
);

CREATE TABLE "competition" (
  "competition_id" int PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "address" text NOT NULL,
  "date_start" date NOT NULL,
  "date_end" date NOT NULL,
  "creator_id" text NOT NULL
);

CREATE TABLE "round" (
  "round_id" int PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "age_group" age_group_enum NOT NULL
);

CREATE TABLE "range" (
  "range_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "target_face_id" int NOT NULL,
  "distance" int NOT NULL,
  "unit_of_length" unit_of_length_enum NOT NULL
);

CREATE TABLE "request_form" (
  "form_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sender_id" int NOT NULL,
  "type" type_request_form_enum NOT NULL,
  "action" action_request_form_enum NOT NULL,
  "competition_id" int NOT NULL,
  "round_id" int NOT NULL,
  "sender_word" text NOT NULL,
  "status" status_enum NOT NULL,
  "reviewer_word" text,
  "reviewed_by" int,
  "create_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "club_enrollment_form" (
  "form_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sender_id" int NOT NULL,
  "sender_word" text NOT NULL,
  "status" status_enum NOT NULL,
  "club_id" int NOT NULL,
  "club_creator_word" text NOT NULL,
  "create_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "equipment" (
  "equipment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "photo_url" text NOT NULL DEFAULT 'https://ghcpcyvethwdzzgyymfp.supabase.co/storage/v1/object/public/User%20Avatar/Equipment_Photo/Default_Equipment.png',
  "description" text
);

CREATE TABLE "round_equipment_compatibility" (
  "round_id" int,
  "equipment_id" int,
  PRIMARY KEY ("round_id", "equipment_id")
);

CREATE TABLE "target_face" (
  "target_face_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "diameter" int NOT NULL,
  "unit_of_length" unit_of_length_enum NOT NULL
);

CREATE TABLE "ai_conversation_history" (
  "account_id" int,
  "prompt_response_order" int,
  "prompt" text NOT NULL,
  "response" text NOT NULL,
  PRIMARY KEY ("account_id", "prompt_response_order")
);

COMMENT ON COLUMN "account"."email_address" IS 'used for authentication and as an account name when log in or sign up';

COMMENT ON COLUMN "account"."fullname" IS 'current world record for longest name existed :))';

COMMENT ON COLUMN "account"."date_of_birth" IS 'used to dynamically calculate age if needed';

COMMENT ON COLUMN "account"."avatar_url" IS 'used to user avatar picture url from supabase storage';

COMMENT ON COLUMN "admin"."admin_id" IS 'not set to increment because we need to manually specify admin_id to authorize existed or just-created accounts, the rule for an account to be admin is that the account_id == admin_id';

COMMENT ON COLUMN "recorder"."recorder_id" IS 'not set to increment because recorder_id must be taken from account_id';

COMMENT ON COLUMN "recorder"."background" IS 'text that other people will see and you want them to know more about you as a recorder';

COMMENT ON COLUMN "archer"."archer_id" IS 'not set to increment because archer_id must be taken from account_id';

COMMENT ON COLUMN "archer"."background" IS 'text that other people will see and you want them to know more about you as an archer';

COMMENT ON COLUMN "club"."age_group" IS 'some clubs are only interested in a group of age';

COMMENT ON TABLE "australia_archery_federation" IS 'those are people who have rights to add new round in round table, new range in range table, new equipment in equipment table, and new target face in target face table for recorders to select when recorders design a competition in event_context table
';

COMMENT ON COLUMN "event_context"."event_context_id" IS 'auto-generated id with format:competition_id-round_id-range_id-end_order, yearly_club_championship_id is not included since it can be null ';

COMMENT ON COLUMN "event_context"."yearly_club_championship_id" IS 'null if competition does not contribute to any yearly club championship';

COMMENT ON COLUMN "event_context"."end_order" IS '1 to whatsoever';

COMMENT ON COLUMN "range"."target_face_id" IS 'type of target face used';

ALTER TABLE "archer" ADD FOREIGN KEY ("archer_id") REFERENCES "account" ("account_id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "recorder" ADD FOREIGN KEY ("recorder_id") REFERENCES "account" ("account_id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "admin" ADD FOREIGN KEY ("admin_id") REFERENCES "account" ("account_id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "australia_archery_federation" ADD FOREIGN KEY ("member_id") REFERENCES "account" ("account_id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "participating" ADD FOREIGN KEY ("participant_id") REFERENCES "archer" ("archer_id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "participating" ADD FOREIGN KEY ("event_context_id") REFERENCES "event_context" ("event_context_id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "event_context" ADD FOREIGN KEY ("yearly_club_championship_id") REFERENCES "yearly_club_championship" ("yearly_club_championship_id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "event_context" ADD FOREIGN KEY ("competition_id") REFERENCES "competition" ("competition_id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "event_context" ADD FOREIGN KEY ("round_id") REFERENCES "round" ("round_id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "event_context" ADD FOREIGN KEY ("range_id") REFERENCES "range" ("range_id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "archer" ADD FOREIGN KEY ("club_id") REFERENCES "club" ("club_id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "request_form" ADD FOREIGN KEY ("sender_id") REFERENCES "account" ("account_id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "request_form" ADD FOREIGN KEY ("competition_id") REFERENCES "competition" ("competition_id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "request_form" ADD FOREIGN KEY ("round_id") REFERENCES "round" ("round_id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "request_form" ADD FOREIGN KEY ("reviewed_by") REFERENCES "recorder" ("recorder_id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "request_form" ADD FOREIGN KEY ("reviewed_by") REFERENCES "admin" ("admin_id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "archer" ADD FOREIGN KEY ("default_equipment_id") REFERENCES "equipment" ("equipment_id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "round_equipment_compatibility" ADD FOREIGN KEY ("round_id") REFERENCES "round" ("round_id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "round_equipment_compatibility" ADD FOREIGN KEY ("equipment_id") REFERENCES "equipment" ("equipment_id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "range" ADD FOREIGN KEY ("target_face_id") REFERENCES "target_face" ("target_face_id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "recording" ADD FOREIGN KEY ("competition_id") REFERENCES "competition" ("competition_id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "recording" ADD FOREIGN KEY ("round_id") REFERENCES "round" ("round_id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "recording" ADD FOREIGN KEY ("recorder_id") REFERENCES "recorder" ("recorder_id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "club_enrollment_form" ADD FOREIGN KEY ("sender_id") REFERENCES "archer" ("archer_id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "club_enrollment_form" ADD FOREIGN KEY ("club_id") REFERENCES "club" ("club_id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "ai_conversation_history" ADD FOREIGN KEY ("account_id") REFERENCES "account" ("account_id") ON DELETE SET NULL ON UPDATE CASCADE;
